name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  workflow_dispatch:
jobs:
  Date:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './rtk-blog/'
    steps:
      - name: Get Date
        run: echo "MY_DATE=$(date +%Y-%m-%d)" >> $GITHUB_ENV
      - name: Get SHA
        run: echo "SHA=${{github.sha}}| tail -c 6" >> $GITHUB_ENV
      - name: Output
        run: echo ${{env.MY_DATE}} and ${{env.SHA}}
      - name: Path
        run: echo ${{env.working-directory}}
