name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  workflow_dispatch:
jobs:
  Date:
    runs-on: ubuntu-latest
    steps:
      # - name: Get current date
      #   id: date
      #   run: echo "{date}=${date +'%Y-%m-%d'}" >> $GITHUB_OUTPUT
      - name: Test with environment variables
        run: echo "MY_DATE=$(date +%Y-%m-%d)" >> $GITHUB_ENV
      - name: Test MY_DATE variable
        run: echo ${{ env.MY_DATE }} and ${${{github.sha}}| tail -c 6}
